### ISSUE TITLE
URL based matching

### ISSUE THREAD

**Issue by guyisra** [pact-foundation/pact-ruby#107]
I am using PACT to mock a service which uses a REST based urls

```
resource/resource_id/system/system_id
```

Is there a way to avoid have a predefined resource_id/system_id which must be used by the consumer and provider? I.e. resource_id should look like a UUID, but it really doesn't matter, as long as its consitent throughout the mocking - if I request resource/resource_id, `resource_id` should use whatever has been sent, as long as it matching that I specificied

I understand there is support for query parameters, is there a way to do this for REST-like url params?

**Comment by uglyog** [comment]
I'm not sure if regex expression work with paths. I'll need to confirm.

**Comment by bethesque** [comment]
It does in the consumer side, but you need to provide a concrete example
for replay on the provider.

**Comment by guyisra** [comment]
how does it work with regex?

**Comment by guyisra** [comment]
@bethesque Can you give an example of how this can be done?

**Comment by bethesque** [comment]
https://github.com/realestate-com-au/pact/wiki/Regular-expressions-and-type-matching-with-Pact

**Comment by johngluckmdsol** [comment]
It would be nice if there were a way to not have to specify a value for the provider.   

I'm wondering if there can be a generator in the :path, something along the lines of path: '/some_path/{some_generator.generate}' .  For example we use lots of uuids and it would be handy to  randomly generate the uuid and be able to use retrieve the value for use in the provider state to make the service call.  Otherwise, we have to map uuids across projects to provider states.  That seems like it could get out of hand.  But maybe I'm missing something?

**Comment by uglyog** [comment]
Generators are defined as part of the V3 specification, which is not implemented for Ruby as yet: https://github.com/pact-foundation/pact-specification/tree/version-3#introduce-example-generators

**Comment by johngluckmdsol** [comment]
Thanks for the quick response :)

**Comment by YOU54F** [comment]
See #318 for latest status on pact-v3 implementation in pact-ruby

Closing this issue as I've linked it to the meta v3 issue and will be implemented as part of that work
