### ISSUE TITLE
Add retries to verification publishing

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby#158]

**Comment by bethesque** [comment]
Copy this code from the pact broker client https://github.com/pact-foundation/pact_broker-client/blob/master/lib/pact_broker/client/retry.rb

**Comment by bangn** [comment]
Hi @bethesque,

I'm having a look at this issue and have some questions related to [pact-foundation/pact_broker-client:lib/pact_broker/client/retry.rb@master](https://github.com/pact-foundation/pact_broker-client/blob/master/lib/pact_broker/client/retry.rb)
- Could you please let me know the reason behind using `while` loop instead of Ruby's `retry` mechanism?
- Should I remove `verbose = options[:verbose]` at [line #35](https://github.com/pact-foundation/pact_broker-client/blob/master/lib/pact_broker/client/retry.rb#L35) as it is not used anywhere else in this class.

**Comment by bethesque** [comment]
> Could you please let me know the reason behind using while loop instead of Ruby's retry mechanism?

It was code copied from another Pact project, and not a lot of thought was put in to it. You're welcome to submit a PR

> Should I remove verbose = options[:verbose] at line #35 as it is not used anywhere else in this class.

Sure.

Why are you asking? Are you having problems with the retries?

**Comment by bethesque** [comment]
This is already done by the way. I will close it.

**Comment by bangn** [comment]
> Why are you asking? Are you having problems with the retries?
No problem with retries. Im just curious while reading the code :D
