### ISSUE TITLE
Database transactions

### ISSUE THREAD

**Issue by jrmhaig** [pact-foundation/pact-ruby#167]
I have recently started using Pact with a Rails project so I am fairly new to this and may not understand everything fully. Apologies if this is a basic query.

In my unit tests (using rspec) I expect individual tests to run in with a clean test database and in transactions that are rolled back afterwards. With `rails pact:verify`, however, I find that the development database is used (rather than test) and all changes persist. This mean that tests could be dependent on each other or any development work and, additionally, a test that causes a change in the database may pass once but then fail on subsequent attempts.

I realise that I can fix this by clearing up the database in the `set_up` and `tear_down` in each `provider_state` but is there a configuration setting that will make Pact behave more like unit tests?

**Comment by bethesque** [comment]
The database clearing magic will be happening somewhere in your spec_helper.rb. That's probably also where your RAILS_ENV is being set. You have two options - require your spec_helper in your pact helper, or (because sometimes you'll want the behaviour to be slightly different) work out where the desired config is being set up in the spec_helper, and copy this in to the pact_helper (or be DRY and move it into a shared location to be required by both).

**Comment by jrmhaig** [comment]
Thanks. You are right; the `RAILS_ENV` is being set in `spec/rails_helper.rb`. The transaction may be a bit more tricky, though, as it appears to be an RSpec configuration option:

```ruby
RSpec.configure do |config|
  config.use_transactional_fixtures = true
end
```

I may have to dig into the RSpec source to see how it does it.

**Comment by jrmhaig** [comment]
I found that with the `database_cleaner` gem I could just put this in my `pact_helper.rb` file:

```ruby
Pact.set_up do
  DatabaseCleaner.strategy = :transaction
  DatabaseCleaner.start
end

Pact.tear_down do
  DatabaseCleaner.clean
end
```

**Comment by bethesque** [comment]
Cool 👍  That's what I use. Can we close this issue?
