### ISSUE TITLE
Support params in `provider_state` (v3)

### ISSUE THREAD

**Issue by jrmhaig** [pact-foundation/pact-ruby#168]
The example on the `README` has a provider state of 'an alligator exists', which can be defined in the provider configuration with:

```ruby
  provider_state 'an alligator exists' do
    ...
  end
```

Is there any way to use some form of pattern matching with `provider_state` so that a single block could be used for both 'an alligator called Tom exists' and 'an alligator called Jerry exists'?

I'm thinking of something similar to https://github.com/cucumber/cucumber/tree/master/cucumber-expressions

**Comment by bethesque** [comment]
The provider state params in v3 will help with this, because you'll be able to pass in a hash of arbitrary params to help set up a provider state. eg `{"name": "an alligator exists", "params": {"name": "Mary"}}`.

I'm not sure when I'll get around to implementing that, so if you're interested in doing a PR for your suggestion, I'd be happy to accept it.

Personally, I always delegate from the provider state DSL to some helper class anyway, so it ends up being something like:

```
provider_state "an alligator called Tom exists" do
  ProviderStateHelper.new.create_alligator("Tom")
end
```

If I'm in a fancy mood, I'll make a fluent DSL so I can do something like:

```
provider_state "an alligator called Tom exists" do
  ProviderStateHelper.new
    .create_alligator("Tom")
    .create_alligator_credit_card("1234123412341234")
    .create_address("28 Swamp St")
end
```

**Comment by bethesque** [comment]
Oh, you can include modules in the provider states code as well, so it could be as little as 

```ruby
provider_state "an alligator called Tom exists" do
  create_alligator("Tom")
end
```

**Comment by jrmhaig** [comment]
Thanks. The v3 format looks good and I'll live with the fixed strings for the time being.

I hadn't considered using a helper class. I'll have a look at that too.

**Comment by YOU54F** [comment]
closing as tracking under pact v3 epic

https://github.com/pact-foundation/pact-ruby/issues/318
